apiVersion: v1
appVersion: "2026summer-alpha"
description: yuuvis client components
name: yuuvis-client
version: 0.16.8
keywords:
- yuuvis
- client
- bpm
home: https://yuuvis.com/scalable-content-services
