apiVersion: v1
appVersion: "2026spring-alpha"
description: yuuvis client components
name: yuuvis-client
version: 0.15.13
keywords:
- yuuvis
- client
- bpm
home: https://yuuvis.com/scalable-content-services
