apiVersion: v1
appVersion: "2026autumn-alpha"
description: yuuvis client components
name: yuuvis-client
version: 0.17.4
keywords:
- yuuvis
- client
- bpm
home: https://yuuvis.com/scalable-content-services
