apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    k8s-app: api-gateway-metrics
    name: api
    yuuvis: "true"
  name: api
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.api.port}}
  selector:
    name: api
  type: ClusterIP