apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: audit
    yuuvis: "true"
    reason: "backwards_compatibility"
    target: registry
  name: audit
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.registry.port}}
  selector:
    name: registry
  type: ClusterIP