apiVersion: batch/v1
kind: Job
metadata:
  name: pre-upgrade-job-2021autumn
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: pre-upgrade-job-2021autumn
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - env:
        - name: YUUVIS_UPDATE_GIT_PROTOCOL
          value: {{.Values.yuuvis.git.protocol}}
        - name: YUUVIS_UPDATE_GIT_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: gitsecret
        - name: YUUVIS_UPDATTE_GIT_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: gitsecret
        - name: YUUVIS_UPDATE_GIT_URL
          value: {{.Values.yuuvis.git.url}}
        - name: YUUVIS_UPDATE_GIT_NAME
          value: {{.Values.yuuvis.git.name}}
        - name: YUUVIS_UPDATE_GIT_BRANCH
          value: {{.Values.yuuvis.git.branch}}
        - name: YUUVIS_UPDATE_GIT_AUTH_PORT
          value: "{{.Values.yuuvis.services.authentication.managePort}}"
        name: pre-upgrade-job-2021autumn
        image: docker.yuuvis.org/yuuvis/update:2021autumn
      imagePullSecrets:
      - name: yuuvisorg
        