{{- if .Values.yuuvis.services.config.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: configservice-pdb
  labels:
    app: {{ .Values.yuuvis.labels.app }}
    name: configservice
spec:
  selector:
    matchLabels:
      name: configservice
  {{- if kindIs "int" .Values.yuuvis.services.config.pdb.minAvailable }}
  minAvailable: {{ .Values.yuuvis.services.config.pdb.minAvailable }}
  {{- end }}
  {{- if kindIs "int" .Values.yuuvis.services.config.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.yuuvis.services.config.pdb.maxUnavailable }}
  {{- end }}
{{- end -}}
