{{- if .Values.yuuvis.services.contentanalyzer.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: contentanalyzer-pdb
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: contentanalyzer
spec:
  selector:
    matchLabels:
      name: contentanalyzer
  {{- if kindIs "int" .Values.yuuvis.services.contentanalyzer.pdb.minAvailable }}
  minAvailable: {{ .Values.yuuvis.services.contentanalyzer.pdb.minAvailable }}
  {{- end }}
  {{- if kindIs "int" .Values.yuuvis.services.contentanalyzer.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.yuuvis.services.contentanalyzer.pdb.maxUnavailable }}
  {{- end }}
{{- end -}}
