apiVersion: batch/v1
kind: Job
metadata:
  name: config-init-{{.Chart.AppVersion}}
spec:
  template:
    spec:
      {{- if or .Values.yuuvis.initjob.nodeAffinity .Values.yuuvis.initjob.podAffinity .Values.yuuvis.initjob.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.initjob.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.initjob.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.initjob.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: config-init
        image: {{.Values.yuuvis.initjob.docker.registry}}/{{.Values.yuuvis.initjob.docker.image}}:{{.Values.yuuvis.initjob.docker.tag}}
        imagePullPolicy: IfNotPresent
        env:
        - name: KEYCLOAKURL
          value: {{.Values.yuuvis.initjob.keycloak.url}}
        - name: KEYCLOAKADMIN
          value: {{.Values.yuuvis.initjob.keycloak.admin}}
        - name: KEYCLOAKPASSOWRD
          value: {{.Values.yuuvis.initjob.keycloak.password}}
        - name: KEYCLOAKINITREALMNAME
          value: {{.Values.yuuvis.initjob.keycloak.realm.name}}
        - name: KEYCLOAKINITREALMUSER
          value: {{.Values.yuuvis.initjob.keycloak.realm.user}}
        - name: KEYCLOAKINITREALMPASSWORD
          value: {{.Values.yuuvis.initjob.keycloak.realm.password}}
        - name: YUUVISAUTHURL
          value: {{.Values.yuuvis.initjob.authurl}}
        - name: CREATEREALM
          value: "{{.Values.yuuvis.initjob.createrealm}}"
        - name: GITSERVER
          value: {{.Values.yuuvis.git.server}}
        - name: GITURL
          value: {{.Values.yuuvis.git.url}}
        - name: GITBRANCH
          value: {{.Values.yuuvis.git.branch}}
        - name: GITNAME
          value: {{.Values.yuuvis.git.name}}
        - name: GITUSER
          valueFrom:
            secretKeyRef:
              key: user
              name: gitsecret
        - name: GITPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: gitsecret
        command: ['sh', '/tmp/script/initgit.sh']
        volumeMounts:
        - mountPath: /yuuvis/data
          name: configyml
        - mountPath: /yuuvis/data/system
          name: systemconfig
        - mountPath: /tmp/script/initgit.sh
          name: initscript
          subPath: initgit.sh
      imagePullSecrets:
      - name: yuuvisorg
      volumes:
      - configMap:
          name: initcommitconfigmap
        name: initscript
      - configMap:
          name: profilesconfigmap
        name: configyml
      - configMap:
          name: systemconfigmap
        name: systemconfig
      restartPolicy: OnFailure
      {{- with .Values.yuuvis.initjob.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.initjob.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.initjob.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.initjob.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}