{{- if .Values.yuuvis.services.index.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: index-pdb
  labels:
    app: {{ .Values.yuuvis.labels.app }}
    name: index
spec:
  selector:
    matchLabels:
      name: index
  {{- if kindIs "int" .Values.yuuvis.services.index.pdb.minAvailable }}
  minAvailable: {{ .Values.yuuvis.services.index.pdb.minAvailable }}
  {{- end }}
  {{- if kindIs "int" .Values.yuuvis.services.index.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.yuuvis.services.index.pdb.maxUnavailable }}
  {{- end }}
{{- end -}}
