apiVersion: v1
data:
  checkgit.sh: |
    cd /tmp
    
    echo git clone
    if git clone  {{.Values.yuuvis.git.protocol}}://$GITUSER:$GITPWD@{{.Values.yuuvis.git.url}} \
        --branch {{.Values.yuuvis.git.branch}}; 
    then
        echo git branch {{.Values.yuuvis.git.branch}} exists
        cd {{.Values.yuuvis.git.name}}
        
        git config user.email yuuvis-init@yuuvis.org
        git config user.name yuuvis-init
        
        echo check if application-prod.yml exists
        if [ ! -f application-prod.yml ]; 
        then 
            echo no application-prod.yml found
            echo create application-prod.yml
            echo "docker.enabled: true" > application-prod.yml
            git add application-prod.yml
            git commit -m "init application-prod.yml, used for common configs of every service"
            git push
        fi
        
        if [ -f application-es.yml ]; 
        then 
            echo application-es.yml exists 
            exit 0
        fi
    fi
    echo 'unexpected git state'
    exit 1  
kind: ConfigMap
metadata:
  name: initconfigserviceconfigmap
