{{- if .Values.yuuvis.services.organization.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: organization-pdb
  labels:
    app: {{ .Values.yuuvis.labels.app }}
    name: organization
spec:
  selector:
    matchLabels:
      name: organization
  {{- if kindIs "int" .Values.yuuvis.services.organization.pdb.minAvailable }}
  minAvailable: {{ .Values.yuuvis.services.organization.pdb.minAvailable }}
  {{- end }}
  {{- if kindIs "int" .Values.yuuvis.services.organization.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.yuuvis.services.organization.pdb.maxUnavailable }}
  {{- end }}
{{- end -}}
