apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: organization
    yuuvis: "true"
    reason: "backwards_compatibility"
    target: system
  name: organization
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: {{.Values.yuuvis.services.system.port}}
  selector:
    name: system
  type: ClusterIP