apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: registry
  name: registry
spec:
  replicas: {{.Values.yuuvis.services.registry.instances}}
  selector:
    matchLabels:
      name: registry
  template:
    metadata:
      labels:
        name: registry
    spec:
      {{- if or .Values.yuuvis.services.registry.nodeAffinity .Values.yuuvis.services.registry.podAffinity .Values.yuuvis.services.registry.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.services.registry.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.registry.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.registry.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-registry
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        imagePullPolicy: {{.Values.initContainer.imagePullPolicy}}
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      containers:
      - name: registry
        image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.services.registry.dockerImage}}:{{ .Values.yuuvis.services.registry.tag }}"
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        {{- if and .Values.yuuvis.livenessProbe.enable .Values.yuuvis.services.registry.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: /manage/info
            port: 7510
         initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
         periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
         timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        {{- end}}
        {{- if .Values.yuuvis.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: {{.Values.yuuvis.readinessProbe.path}}
            port: {{.Values.yuuvis.services.registry.port}}
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
        {{- end}}
        resources:
          requests:
            memory: {{.Values.yuuvis.services.registry.requests.memory}}
        env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.services.registry.java.maxHeap}}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.services.registry.profiles}}
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: yuuvis-common-env
              key: CONFIGSERVICEURL
        ports:
        - containerPort: {{.Values.yuuvis.services.registry.port}}
      restartPolicy: Always
      automountServiceAccountToken: false
      {{- with .Values.yuuvis.services.registry.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.services.registry.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.registry.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.services.registry.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.yuuvis.image.imagePullSecret }}