apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: repository
  name: repository
spec:
  replicas: {{.Values.yuuvis.services.repository.instances}}
  selector:
    matchLabels:
      name: repository
  template:
    metadata:
      labels:
        name: repository
    spec:
      {{- if or .Values.yuuvis.services.repository.nodeAffinity .Values.yuuvis.services.repository.podAffinity .Values.yuuvis.services.repository.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.services.repository.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.repository.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.repository.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-repository
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        imagePullPolicy: {{.Values.initContainer.imagePullPolicy}}
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      containers:
      - name: repository
        image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.services.repository.dockerImage}}:{{ .Values.yuuvis.services.repository.tag }}"
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        {{- if .Values.yuuvis.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: {{.Values.yuuvis.livenessProbe.path}}
            port: {{.Values.yuuvis.services.repository.port}}
          initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        {{- end}}
        {{- if .Values.yuuvis.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: {{.Values.yuuvis.readinessProbe.path}}
            port: {{.Values.yuuvis.services.repository.port}}
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
        {{- end}}
        resources:
          requests:
            memory: {{.Values.yuuvis.services.repository.requests.memory}}
        env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.services.repository.java.maxHeap}}
        - name: REQUESTS_MAXPARALLEL
          value: {{quote .Values.yuuvis.services.repository.maxRequests}}  
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.services.repository.profiles}}
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: yuuvis-common-env
              key: CONFIGSERVICEURL
        ports:
        - containerPort: {{.Values.yuuvis.services.repository.port}}
        {{- if .Values.yuuvis.services.repository.volumeMounts }}
        volumeMounts:
{{ tpl .Values.yuuvis.services.repository.volumeMounts . | indent 8 }}
        {{- end }}
      restartPolicy: Always
      automountServiceAccountToken: false
      {{- with .Values.yuuvis.services.repository.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.services.repository.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.repository.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.services.repository.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.yuuvis.image.imagePullSecret }}
      {{- if .Values.yuuvis.services.repository.volumes }}
      volumes:
{{ tpl .Values.yuuvis.services.repository.volumes . | indent 6 }}
      {{- end}}