apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: textextractor
  name: textextractor
spec:
  replicas: {{.Values.yuuvis.services.textextractor.instances}}
  selector:
    matchLabels:
      name: textextractor
  template:
    metadata:
      labels:
        name: textextractor
    spec:
      {{- if or .Values.yuuvis.services.textextractor.nodeAffinity .Values.yuuvis.services.textextractor.podAffinity .Values.yuuvis.services.textextractor.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.services.textextractor.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.textextractor.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.services.textextractor.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-textextractor
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        imagePullPolicy: {{.Values.initContainer.imagePullPolicy}}
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      containers:
      - name: textextractor
        image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.services.textextractor.dockerImage}}:{{ .Values.yuuvis.services.textextractor.tag }}"
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        {{- if .Values.yuuvis.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: {{.Values.yuuvis.livenessProbe.path}}
            port: {{.Values.yuuvis.services.textextractor.port}}
          initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        {{- end}}
        {{- if .Values.yuuvis.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: {{.Values.yuuvis.readinessProbe.path}}
            port: {{.Values.yuuvis.services.textextractor.port}}
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
       {{- end}}
        resources:
          requests:
            memory: {{.Values.yuuvis.services.textextractor.requests.memory}}
        env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.services.textextractor.java.maxHeap}}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.services.textextractor.profiles}}
        - name: SPRING_CLOUD_CONFIG_URI
          valueFrom:
            configMapKeyRef:
              name: yuuvis-common-env
              key: CONFIGSERVICEURL
        ports:
        - containerPort: {{.Values.yuuvis.services.textextractor.port}}
      restartPolicy: Always
      automountServiceAccountToken: false
      {{- with .Values.yuuvis.services.textextractor.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.services.textextractor.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.textextractor.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.services.textextractor.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      - name: {{ .Values.yuuvis.image.imagePullSecret }}