apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: repositorymanager-cmis
  name: repositorymanager-cmis
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8090
  selector:
    name: repositorymanager-cmis
  type: ClusterIP