{
 "title": "Momentum Applications (Services)",
 "description": "Dashboard for inspection of applications in momentum cluster at service level",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace!~\"cert-manager\", namespace!~\"ingress-nginx\",  namespace!~\"kube-system\", namespace!~\"infrastructure\",  namespace!~\"monitoring\"},namespace)"
    }
   },
   {
    "name": "application",
    "label": "application",
    "query": {
     "query": "label_values({namespace=\"$namespace\", service!~\".*prometheus.*\", service!~\".*kubelet.*\"}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{service=\"$application\"})"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{service=\"$application\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$application\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{service=\"$application\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "HTTP Requests  per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{service=\"$application\",uri!~\".*manage.*\"}[1m]))",
     "legendFormat": "HTTP Requests -"
    }
   ]
  },
  {
   "title": "Response time in seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{service=\"$application\",uri!~\".*manage.*\", status=~\"2..\"}[1m]))/sum(rate(http_server_requests_seconds_count{service=\"$application\",uri!~\".*manage.*\", status=~\"2..\"}[1m]))",
     "legendFormat": "Avg response time"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(logback_events_total{namespace=\"$namespace\", service=\"$application\"}[1m])) by (level) ",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "HTTP Error Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{service=\"$application\",uri!~\".*manage.*\", outcome=\"CLIENT_ERROR\", status=\"422\"})",
     "legendFormat": "CLIENT_ERROR (422) -"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{service=\"$application\",uri!~\".*manage.*\", outcome=\"CLIENT_ERROR\", status=\"404\"})",
     "legendFormat": "CLIENT_ERROR (404) -"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{service=\"$application\",uri!~\".*manage.*\", outcome=\"SERVER_ERROR\", status=\"503\"})",
     "legendFormat": "CLIENT_ERROR (503) -"
    },
    {
     "expr": "sum(http_server_requests_seconds_max{service=\"$application\",uri!~\".*manage.*\", outcome!~\"SUCCESS\", outcome!~\"REDIRECTION\", status!~\"404\", status!~\"422\"})",
     "legendFormat": "Remaining Errors"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$application\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$application\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$application\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$application\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service=\"$application\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{service=\"$application\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{service=\"$application\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(system_cpu_usage{service=\"$application\"}) ",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Thread Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tomcat_threads_busy_threads{service=\"$application\"})",
     "legendFormat": "Used - "
    },
    {
     "expr": "avg(tomcat_threads_current_threads{service=\"$application\"})",
     "legendFormat": "Allocated - "
    },
    {
     "expr": "avg(tomcat_threads_config_max_threads{service=\"$application\"})",
     "legendFormat": "Max available -"
    },
    {
     "expr": "avg(jetty_threads_busy{service=\"$application\"})",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "avg(jetty_threads_current{service=\"$application\"})",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "avg(jetty_threads_config_max{service=\"$application\"})",
     "legendFormat": "JETTY - MAX"
    }
   ]
  }
 ]
}