{{- if and .Values.yuuvis.services.coreextensions.enabled .Values.yuuvis.services.coreextensions.config.serviceuser.createnewsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.secretname }}
type: Opaque
data:
  tenant: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.tenant | b64enc | quote }}
  user: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.username | b64enc | quote }}
  password: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.password | b64enc | quote }}
{{- if and .Values.yuuvis.services.coreextensions.config.serviceuser.createnewsecret  .Values.yuuvis.services.coreextensions.config.serviceuser.createuser.enabled }}
  email: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.createuser.email | b64enc | quote }}
  keycloakadmin: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.createuser.keycloak.admin | b64enc | quote }}
  keycloakadminpassword: {{ .Values.yuuvis.services.coreextensions.config.serviceuser.createuser.keycloak.adminpassword | b64enc | quote }}
{{- end -}}
{{- end -}}
