apiVersion: v1
appVersion: "2023winter"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.4.0
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
