apiVersion: v1
appVersion: "2026autumn-alpha"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.13.2
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
