apiVersion: v1
appVersion: "2026spring-alpha"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.11.3
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
