apiVersion: v1
appVersion: "2023autumn"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.3.0
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
