apiVersion: v1
appVersion: "2020 winter"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.1.0
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
