apiVersion: v1
appVersion: "2025winter"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.11.6
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
