apiVersion: v1
appVersion: "2024summer"
description: yuuvis rendition components
name: yuuvis-rendition
version: 0.6.2
keywords:
- yuuvis
- rendition
home: https://yuuvis.com/scalable-content-services
