apiVersion: v1
data:
  createSelfsignedCert.bash: |-

    PASSWORD={{.Values.yuuvis.mailarchiving.selfSignedCert.password}}
    REINSTALL={{.Values.yuuvis.mailarchiving.selfSignedCert.reinstallifexists}}
    echo "Checking if secret exists..."
    SECRET_EXIST=$(kubectl get secret mailarchiving-smtp-selfsigned-tls-secret > /dev/null 2>&1 && echo "yes" || echo "no")

    if [ "$SECRET_EXIST" = "yes" ]; then
      if [ "$REINSTALL" = "true" ]; then
        kubectl delete secret mailarchiving-smtp-selfsigned-tls-secret
      else
        echo "Secret mailarchiving-smtp-selfsigned-tls-secret already exists. Skipping creation."
        exit 0
      fi
    fi

    echo "keytool -genkey"
    keytool -genkey -alias mailarchiving-smtp-tls -keyalg RSA -keystore mailarchivingsmtp.jks -validity 36500 -storepass "$PASSWORD" -dname "CN=mailarchiving-smtp-tls, OU=mailarchiving, O=mailarchiving, L=Berlin, ST=Berlin, C=de" -keypass "$PASSWORD"

    echo "keytool convert pkcs"
    keytool -importkeystore -srckeystore mailarchivingsmtp.jks -destkeystore mailarchivingsmtp.p12 -deststoretype PKCS12 -storepass "$PASSWORD" -srcstorepass "$PASSWORD"

    echo "k8s create mailarchiving-smtp-selfsigned-tls-secret"
    kubectl create secret generic mailarchiving-smtp-selfsigned-tls-secret --from-file=mailarchivingsmtp.p12 --from-literal=password="$PASSWORD"

    rm -f mailarchivingsmtp.jks mailarchivingsmtp.p12
kind: ConfigMap
metadata:
  name: selfsignedcert