apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
  name: mailarchiving-smtp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mailarchiving-smtp
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - delete
  - list
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mailarchiving-smtp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mailarchiving-smtp
subjects:
- kind: ServiceAccount
  name: mailarchiving-smtp