apiVersion: v1
data:
  massmtp-prod.yml: |
    mas-storage:
      uri: {{.Values.yuuvis.mailarchiving.smtp.profiles.masstorage.uri}}
    #mas-smtp:
       #port: 25000 Port on which SMTP will listen for the incoming messages. Must be greater than 1024. Default is 25000.
       #base-auth: #credentials in case of using basic authentication
         #username:
         #password:
      #tls:
        #require-tls: false #switch to true if using TLS
        #key-store-file: #path to the file which holds SSL certificate
        #key-store-pass: #password for accessing key-store-file
        #key-store-type: # default value is PCK12
      #message-mode: JOURNAL  #expected type of message through smtp, set to receive journal reports (JOURNAL), Non-delivery reports, ie. alternate messages (ALTERNATE) or ordinary mails (NORMAL)
      #restrictions: #Allowed senders and recipients of journaling reports for Exchange Online connection
         #allowed-senders: #sender1@sample.de, sender2@mail.com #comma separated mail addresses of accepted senders, should be adapted according to the Exchange configuration
         #allowed-recipients: #recipient1@example.de, recipient2@exchange.com #comma separated mail addresses of accepted senders, should be adapted according to the Exchange configuration
      #obfuscate-message: true #Indicates should received mail be logged and stored with hidden sensitive information.
kind: ConfigMap
metadata:
  name: massmtp-prod