apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
  name: mailarchiving-smtp-create-selfsigned-cert-job-{{ .Release.Revision }}
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: mailarchiving-smtp-tls
          image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.mailarchiving.selfSignedCert.image}}:{{.Values.yuuvis.mailarchiving.selfSignedCert.tag}}"
          imagePullPolicy: {{.Values.yuuvis.image.imagePullPolicy}}
          command: [ "/bin/bash" ]
          args: [ "/mailarchiving/script/createSelfsignedCert.bash" ]
          volumeMounts:
            - mountPath: /mailarchiving/script/createSelfsignedCert.bash
              name: createscript
              subPath: createSelfsignedCert.bash
      imagePullSecrets:
        - name: {{.Values.yuuvis.image.imagePullSecret}}
      volumes:
        - configMap:
            name: selfsignedcert
          name: createscript
      restartPolicy: {{.Values.yuuvis.image.restartPolicy}}
      serviceAccountName: mailarchiving-smtp
      {{- if .Values.yuuvis.mailarchiving.initContainer.securityContext }}
      securityContext:
      {{- toYaml .Values.yuuvis.mailarchiving.initContainer.securityContext | nindent 8 }}
      {{- end }}
      {{- with .Values.yuuvis.mailarchiving.initContainer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}