{{- if .Values.yuuvis.client.client.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: client
  name: client
spec:
  replicas: {{.Values.yuuvis.client.client.instances}}
  selector:
    matchLabels:
      name: client
  template:
    metadata:
      labels:
        name: client
    spec:
      automountServiceAccountToken: false
      {{- if or .Values.yuuvis.client.client.nodeAffinity .Values.yuuvis.client.client.podAffinity .Values.yuuvis.client.client.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.client.client.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.client.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.client.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: client-add-required-resources
        image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.client.client.initContainerImage}}
        imagePullPolicy: IfNotPresent
        command: [ 'sh', '/yuuvis/data/script/addresources.sh' ]
        env:
        - name: YUUVIS_TENANT
          valueFrom:
            secretKeyRef:
              key: tenant
              name: {{ .Values.yuuvis.init.configuser.secretname }}
        - name: YUUVIS_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: {{ .Values.yuuvis.init.configuser.secretname }}
        - name: YUUVIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.yuuvis.init.configuser.secretname }}
        {{- if .Values.yuuvis.common.env }}
        {{- toYaml .Values.yuuvis.common.env | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /yuuvis/data/script
          name: configureapps
        - mountPath: /yuuvis/data/resources
          name: clientresources
        - mountPath: /tmp
          name: tmp
      containers:
      - image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.client.client.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: client
        ports:
        - containerPort: 80
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        {{- if .Values.yuuvis.common.env }}
        env:
        {{- toYaml .Values.yuuvis.common.env | nindent 8 }}
        {{- end }}
        {{- if .Values.yuuvis.client.client.resources }}
        resources: {{- toYaml .Values.yuuvis.client.client.resources | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret }}
      restartPolicy: Always
      {{- with .Values.yuuvis.client.client.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.client.client.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.client.client.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.client.client.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{.Values.yuuvis.securityContext.fsGroup}}
        runAsGroup: {{.Values.yuuvis.securityContext.runAsGroup}}
        runAsUser: {{.Values.yuuvis.securityContext.runAsUser}}
        runAsNonRoot: {{.Values.yuuvis.securityContext.runAsNonRoot}}
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - emptyDir: {}
        name: tmp
      - configMap:
          name: clientinit
        name: configureapps
      - configMap:
          name: clientresources
        name: clientresources
{{- end }}      