{{- if .Values.yuuvis.bpm.engine.enabled -}}
apiVersion: v1
kind: ConfigMap
data:
  bpm-engine.yml: |
{{ tpl .Values.yuuvis.bpm.engine.configyml . | indent 4 }}
metadata:
  name: bpmengineresources
{{- end }}