apiVersion: v1
appVersion: "1.0"
description: yuuvis mailarchiving mailbox components
name: yuuvis-mailarchiving-mailbox
version: 0.1.0
keywords:
  - yuuvis
  - mailarchivingmailbox
home: https://yuuvis.com/scalable-content-services