{{- if .Values.yuuvis.management.console.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: console-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.management.console.api.config.db.user | b64enc | quote }}
  password: {{ .Values.yuuvis.management.console.api.config.db.password | b64enc | quote }}
{{- end}}