{{- if .Values.yuuvis.management.console.deploy }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: management-console
  name: management-console
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 5000
  selector:
    app: management-console
  type: ClusterIP
{{- end}}