{{- if .Values.yuuvis.management.console.deploy }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: management-console-client
    yuuvis: "true"
  name: management-console-client
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    name: management-console-client
{{- end}}
