{{- if .Values.yuuvis.management.console.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: management-console-client
  name: management-console-client
spec:
  replicas: {{.Values.yuuvis.management.console.client.instances}}
  selector:
    matchLabels:
      name: management-console-client
  template:
    metadata:
      labels:
        name: management-console-client
    spec:
      containers:
      - name: console-client
        image: "{{.Values.yuuvis.management.console.client.dockerImage}}"
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: client-configmap-volume
          mountPath: /usr/share/nginx/html/assets/config.json
          subPath: config.json
      volumes:
      - name: client-configmap-volume
        configMap:
          name: management-console-client-config
          items:
          - key: config.json
            path: config.json
      restartPolicy: Always
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret}}
{{- end}}
