{{- if .Values.yuuvis.management.console.deploy }}
apiVersion: v1
data:
  .env: |+
    # Host of the managed yuuvis installation
    YUUVIS_HOST={{.Values.yuuvis.management.console.api.config.host}}

    # Keycloak service account settings
    YUUVIS_KEYCLOAK_HOST={{.Values.yuuvis.management.console.api.config.keycloak}}
    YUUVIS_KEYCLOAK_REALM={{.Values.yuuvis.management.console.api.config.realm}}
    YUUVIS_KEYCLOAK_CLIENT_ID={{.Values.yuuvis.management.console.api.config.client}}
    YUUVIS_KEYCLOAK_CLIENT_SECRET={{.Values.yuuvis.management.console.api.config.clientsecret}}

    # Where the api is hosted (required for oauth provider redirects)
    YMC_API_HOST={{.Values.yuuvis.management.console.api.config.apiHost}}
    YMC_CLIENT_HOST={{.Values.yuuvis.management.console.api.config.clientHost}}
    YMC_API_TITLE=yuuvis® Impulse management console

    # JWT settings
    JWT_ACCESS_TOKEN_SECRET={{.Values.yuuvis.management.console.api.config.jwt.token.access}}
    JWT_ACCESS_TOKEN_EXPIRATION_TIME=1m
    JWT_REFRESH_TOKEN_SECRET={{.Values.yuuvis.management.console.api.config.jwt.token.refresh}}
    JWT_REFRESH_TOKEN_EXPIRATION_TIME=7d

    # Database connection settings
    DB_HOST={{.Values.yuuvis.management.console.api.config.db.host}}
    DB_PORT={{.Values.yuuvis.management.console.api.config.db.port}}
    DB_NAME={{.Values.yuuvis.management.console.api.config.db.name}}
    DB_USER={{.Values.yuuvis.management.console.api.config.db.user}}
    DB_PWD={{.Values.yuuvis.management.console.api.config.db.password}}

    # SMTP server settings
    SMTP_HOST={{.Values.yuuvis.management.console.api.config.smtp.host}}
    SMTP_PORT={{.Values.yuuvis.management.console.api.config.smtp.port}}
    SMTP_USER={{.Values.yuuvis.management.console.api.config.smtp.user}}
    SMTP_PWD={{.Values.yuuvis.management.console.api.config.smtp.password}}
    SMTP_FROM={{.Values.yuuvis.management.console.api.config.smtp.from}}
    
    # service account client for interacting with yuuvis and keycloak itself
    IP_KEYCLOAK_API_CLIENT_ID={{.Values.yuuvis.management.console.api.config.ip.keycloak.api.id}}
    IP_KEYCLOAK_API_CLIENT_SECRET={{.Values.yuuvis.management.console.api.config.ip.keycloak.api.secret}}

    # Keycloak that holds the users of the management console
    IP_KEYCLOAK_CLIENT_ID={{.Values.yuuvis.management.console.api.config.ip.keycloak.client.id}}
    IP_KEYCLOAK_CLIENT_SECRET={{.Values.yuuvis.management.console.api.config.ip.keycloak.client.secret}}
    IP_KEYCLOAK_REALM={{.Values.yuuvis.management.console.api.config.ip.keycloak.realm}}
    IP_KEYCLOAK_HOST={{.Values.yuuvis.management.console.api.config.ip.keycloak.host}}
kind: ConfigMap
metadata:
  name: console-app-config
{{- end}}