yuuvis:
  image:
    imagePullPolicy: Always
    imagePullSecret: yuuvisorg
  labels:
    app: yuuvis
  configservice:
    url: http://configservice/config
  livenessProbe:
    enable: false
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 10
    path: /manage/info
  readinessProbe:
    enable: true
    initialDelaySeconds: 0
    periodSeconds: 30
    timeoutSeconds: 5
    path: /manage/health
  metricsservice:
    dockerImage: docker.yuuvis.org/ultimate/metrics:1.2.0
    profiles: postgres,dbs
    instances: 1
    java:
      maxHeap: -Xmx128m
  apitm:
    dockerImage: docker.yuuvis.org/yuuvis/api-tm:1.3.0
    profiles: prod,docker,kubernetes,oauth2
    instances: 1
    java:
      maxHeap: -Xmx128m
    client:
      rooturl: https://changeme
     
initContainer:
  command: "until wget -q --spider http://configservice/manage/health; do echo waiting for configservice; sleep 11; done;"
