yuuvis:
  image:
    imagePullPolicy: Always
    imagePullSecret: yuuvisorg
  labels:
    app: yuuvis
  configservice:
    url: http://configservice/config
  livenessProbe:
    enable: false
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 10
    path: /manage/info
  readinessProbe:
    enable: true
    initialDelaySeconds: 0
    periodSeconds: 30
    timeoutSeconds: 5
    path: /manage/health
  metricsservice:
    dockerImage: docker.yuuvis.org/yuuvis/metrics:1.2.0
    profiles: postgres,dbs
    instances: 1
    java:
      maxHeap: -Xmx128m
  apitm:
    dockerImage: docker.yuuvis.org/yuuvis/tenant-management:1.4.0
    profiles: prod,docker,kubernetes,oauth2
    instances: 1
    java:
      maxHeap: -Xmx128m
    client:
      rooturl: https://changeme
    # if e.g. the keycloak has been deployed with a self signed cert 
    # the certs mounted at /etc/yuuvis/certs will be added to the used java truststore 
    # at the start of the container
    volumes: |
      - name: keycloak-tls-selfsigned
        secret:
          defaultMode: 420
          secretName: keycloak-selfsigned-cert-secret
    volumeMounts: |
      - mountPath: /etc/yuuvis/certs
        name: keycloak-tls-selfsigned
     
initContainer:
  command: "until wget -q --spider http://configservice/manage/health; do echo waiting for configservice; sleep 11; done;"
