apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    yuuvis: "true"
    name: api-web
  name: api-web
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7550
  selector:
    name: api-web
  type: ClusterIP
