apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: api-web
  name: api-web
spec:
  replicas: {{.Values.yuuvis.client.apiweb.instances }}
  selector:
    matchLabels:
      name: api-web
      yuuvislog: "true"
  template:
    metadata:
      labels:
        name: api-web
        yuuvislog: "true"
    spec:
      {{- if or .Values.yuuvis.client.apiweb.nodeAffinity .Values.yuuvis.client.apiweb.podAffinity .Values.yuuvis.client.apiweb.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.client.apiweb.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.apiweb.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.apiweb.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
      - name: init-api-web
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
        imagePullPolicy: IfNotPresent
      containers:
      - env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.client.apiweb.java.maxHeap}}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{ .Values.yuuvis.configservice.url }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.client.apiweb.profiles}}
        image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.client.apiweb.dockerImage }}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        {{- if .Values.yuuvis.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: /manage/info
            port: 7550
          initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        {{- end}}
        {{- if .Values.yuuvis.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 7550
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
        {{- end}}
        name: api-web
        ports:
        - containerPort: 7550
          protocol: TCP
      imagePullSecrets:
      - name: {{ .Values.yuuvis.image.imagePullSecret }}
      restartPolicy: Always
      {{- with .Values.yuuvis.client.apiweb.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.client.apiweb.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.api.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.client.apiweb.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}