apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: architect
  name: architect
spec:
  replicas: 1
  selector:
    matchLabels:
      name: architect
  template:
    metadata:
      labels:
        name: architect
    spec:
      containers:
      - image: {{.Values.yuuvis.client.architect.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: architect
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: clientsecret
      restartPolicy: Always