apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: client
  name: client
spec:
  replicas: {{.Values.yuuvis.client.client.instances}}
  selector:
    matchLabels:
      name: client
  template:
    metadata:
      labels:
        name: client
    spec:
      containers:
      - image: {{.Values.yuuvis.client.client.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: client
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret }}
      restartPolicy: Always