{{- if .Values.yuuvis.init.configuser.createnewsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.yuuvis.init.configuser.secretname }}
type: Opaque
data:
  tenant: {{ .Values.yuuvis.init.configuser.tenant | b64enc | quote }}
  user: {{ .Values.yuuvis.init.configuser.username | b64enc | quote }}
  password: {{ .Values.yuuvis.init.configuser.password | b64enc | quote }}
{{- end -}}
