apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: custom
    yuuvis: "true"
  name: custom
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: custom
  type: ClusterIP