apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: dashlet365
    yuuvis: "true"
  name: dashlet365
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8099
  type: ClusterIP
  selector:
    name: dashlet365
