apiVersion: batch/v1
kind: Job
metadata:
  name: userservice-init-config
spec:
  template:
    spec:
      containers:
      - name: userservice-init-config
        image: {{.Values.yuuvis.client.userservice.initContainerImage}}
        imagePullPolicy: IfNotPresent
        command: ['bash', '/yuuvis/script/init.bash']
        volumeMounts:
        - mountPath: /yuuvis/data
          name: configyml
        - mountPath: /yuuvis/script/init.bash
          name: initscript
          subPath: init.bash
      volumes:
      - configMap:
          name: adduserserviceconfigconfigmap
        name: initscript
      - configMap:
          name: userserviceconfigconfigmap
        name: configyml
      restartPolicy: OnFailure
