apiVersion: v1
kind: Secret
metadata:
  name: init-userservice-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.client.userservice.database.privilege.user | b64enc | quote }}
  password: {{ .Values.yuuvis.client.userservice.database.privilege.password | b64enc | quote }}