apiVersion: v1
kind: Secret
metadata:
  name: office365-secret
type: Opaque
data:
  user: {{ .Values.yuuvis.client.office365.user | b64enc | quote }}
  password: {{ .Values.yuuvis.client.office365.password | toString | b64enc | quote }}
