apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    yuuvis: "true"
    name: office365
  name: office365
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8091
  selector:
    name: office365
