apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    yuuvis: "true"
    name: sothook
  name: sothook
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 10779
  selector:
    name: sothook
  type: ClusterIP