apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenantmanagement
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
- apiGroups:
    - ""  # Core API
  resources:
    - secrets
  verbs:
    - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenantmanagement
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenantmanagement
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenantmanagement
subjects:
- kind: ServiceAccount
  name: tenantmanagement
