apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: userservice
  name: userservice
spec:
  replicas: {{.Values.yuuvis.client.userservice.instances}}
  selector:
    matchLabels:
      name: userservice
  template:
    metadata:
      labels:
        name: userservice
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.client.userservice.java.maxHeap}}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{ .Values.yuuvis.configservice.url }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.client.userservice.profiles}}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: userservice-dbsecret
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              key: password
              name: userservice-dbsecret
        - name: DB_HOST
          value: {{.Values.yuuvis.client.userservice.database.address}}
        - name: DB_PORT
          value: {{.Values.yuuvis.client.userservice.database.port | quote }}
        - name: DB_NAME
          value: {{.Values.yuuvis.client.userservice.database.name}}
        image: {{.Values.yuuvis.client.userservice.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: userservice
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret }}
      initContainers:
      {{- if .Values.yuuvis.client.userservice.database.createdb }}
      - command:
        - sh
        - /yuuvis/script/initdb.sh
        env:
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              key: user
              name: init-userservice-dbsecret
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: init-userservice-dbsecret
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              key: user
              name: userservice-dbsecret
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              key: password
              name: userservice-dbsecret
        - name: DBNAME
          value: {{.Values.yuuvis.client.userservice.database.name}}
        image: {{.Values.yuuvis.client.userservice.initContainerImage}}
        imagePullPolicy: Always
        name: init-database
        volumeMounts:
        - mountPath: /yuuvis/script/initdb.sh
          name: initdbscript
          subPath: initdb.sh
      {{- end}}
      - name: init-config
        image: docker.yuuvis.org/yuuvis/helper/create-selfsigned-cert:latest
        imagePullPolicy: IfNotPresent
        command: ['bash', '/yuuvis/script/init.bash']
        volumeMounts:
        - mountPath: /yuuvis/script/init.bash
          name: initscript
          subPath: init.bash
      restartPolicy: Always
      volumes:
      - configMap:
          name: inituserserviceconfigmap
        name: initscript
      {{- if .Values.yuuvis.client.userservice.database.createdb }}
      - configMap:
          name: inituserservicedbconfigmap
        name: initdbscript
      {{- end}}