apiVersion: v1
kind: Secret
metadata:
  name: userservice-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.client.userservice.database.user | b64enc | quote }}
  password: {{ .Values.yuuvis.client.userservice.database.password | b64enc | quote }}