apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: viewer
  name: viewer
spec:
  replicas: {{.Values.yuuvis.client.viewer.instances}}
  selector:
    matchLabels:
      name: viewer
  template:
    metadata:
      labels:
        name: viewer
    spec:
      {{- if or .Values.yuuvis.client.viewer.nodeAffinity .Values.yuuvis.client.viewer.podAffinity .Values.yuuvis.client.viewer.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.client.viewer.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.viewer.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.client.viewer.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.client.viewer.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        {{- if .Values.yuuvis.livenessProbe.enable }}
        livenessProbe:
          httpGet:
            path: /manage/health
            port: 9000
          initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        {{- end}}
        {{- if .Values.yuuvis.readinessProbe.enable }}
        readinessProbe:
          httpGet:
            path: /manage/health
            port: 9000
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
        {{- end}}
        name: viewer
        ports:
        - containerPort: 9000
          protocol: TCP
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret }}
      restartPolicy: Always
      {{- with .Values.yuuvis.client.viewer.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.client.viewer.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.api.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.client.viewer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
