{{- if .Values.yuuvis.bpm.modeler.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: bpm-modeler-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.bpm.modeler.database.user | b64enc | quote }}
  password: {{ .Values.yuuvis.bpm.modeler.database.password | b64enc | quote }}
{{- end }}