{{- if and .Values.yuuvis.bpm.modeler.enabled .Values.yuuvis.bpm.modeler.database.createdb}}
apiVersion: v1
kind: Secret
metadata:
  name: init-bpmmodler-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.bpm.modeler.database.privilege.user | b64enc | quote }}
  password: {{ .Values.yuuvis.bpm.modeler.database.privilege.password | b64enc | quote }}
{{- end}}