imageCredentials:
  yuuvisorg:
    registry: docker.yuuvis.org
    username:
    password:
yuuvis:
  labels:
    app: yuuvis
  image:
    imagePullPolicy: Always
    dockerRegistry: docker.yuuvis.org
    imagePullSecret: yuuvisorgstorage
  configservice:
    url: http://system.yuuvis #change value if system is in another namespace not yuuvis e.g. http://system.2024winter
  mailarchiving:
    initContainer:
      image: docker.yuuvis.org/yuuvis/helper/init-helper:latest
      tolerations: [ ]
      nodeAffinity: { }
      securityContext: { }
      restartPolicy: OnFailure
      imagePullPolicy: IfNotPresent
    gitConfigInitJob:
      backoffLimit: 3
      ttlSecondsAfterFinished: 3600 #job will be deleted after 1 hour
    exchangeOnPremPasswordSecret:
      enabled: false
      name: exchange-onprem-secret-name # please change the value if it is in script different
      key: exchange-onprem-secret-key # please change the value if it is in script different
    exchangeOnlineSecret:
      enabled: false
      name: exchange-online-secret-name # please change the value if it is in script different
      key: exchange-online-secret-key # please change the value if it is in script different
    storage:
      instances: 1
      dockerRegistry: docker.yuuvis.org/yuuvis/mailarchiving-storage
      tag: 2.2.1
      restartPolicy: Always
      resources:
        requests:
          cpu: "0.2"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2000Mi"
      java:
        maxHeap: -Xmx256m -XX:+ExitOnOutOfMemoryError
      dms:
        url: #add value
        username: #add value
        tenant: #add value
        passwordSecret:
          name: dms-secret-name # please change the value if it is in script different
          key: dms-secret-key # please change the value if it is in script different
      port: 8130
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
        runAsNonRoot: true
      livenessProbe:
        enable: true
        initialDelaySeconds: 300
        periodSeconds: 30
        timeoutSeconds: 10
        path: /manage/info
      readinessProbe:
        enable: true
        initialDelaySeconds: 0
        periodSeconds: 30
        timeoutSeconds: 5
        path: /manage/health
      pdb:
        # pdb requires instances > 1 and  minAvailable < instances,
        # otherwise draining nodes will deadlock!
        enabled: false
        # set `minAvailable: null` if you want to use maxUnavailable instead
        minAvailable: 1
      nodeSelector: { }
      priorityClassName: ""
      tolerations: [ ]
      nodeAffinity: { }
      podAffinity: { }
      podAntiAffinity: { }
# please change value of system service namespace e.g. http://system.2024winter
initContainer:
  command: "until wget -q --spider http://system.yuuvis/manage/health; do echo waiting for config; sleep 11; done;"
  image: library/busybox
  tag: 1.36
  imagePullPolicy: IfNotPresent
  securityContext: { }