apiVersion: v1
data:
  repositorymanager{{.Values.yuuvis.repositorymanager.profile}}init.bash: |
    until wget -q --spider http://configservice.yuuvis/manage/health;
    do 
      echo 'waiting for configservice'; 
      sleep 11; 
    done;
    
    echo 'test if config exists'
    getrmyml=$(curl -s -o /dev/null -w "%{http_code}" http://configservice.yuuvis/api/resources/repositorymanager-{{.Values.yuuvis.repositorymanager.profile}}.yml)
    
    echo "config result $getrmyml"
    
    if [ $getrmyml = 200 ]
      then
        echo 'repositorymanager yml already exists'
        exit 0
    elif [ $getrmyml = 404 ]
    then
      echo 'must create repositorymanager.yml'
      postyml=$(curl -POST -w "%{http_code}" -F "resource=@/yuuvis/data/repositorymanager-{{.Values.yuuvis.repositorymanager.profile}}.yml" http://configservice.yuuvis/api/resources/repositorymanager-{{.Values.yuuvis.repositorymanager.profile}}.yml)
    
      if [ $postyml != 200 ]
      then
        echo 'post repositorymanager yml failed'
        exit 1
      else
        echo 'repositorymanager yml already exists'
        exit 0
      fi
    fi
    
    exit 1
kind: ConfigMap
metadata:
  name: initrepositorymangerconfigmap
