apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-repositorymanager
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: repositorymanager
  name: repositorymanager
spec:
  replicas: {{.Values.yuuvis.repositorymanager.instances}}
  selector:
    matchLabels:
      name: repositorymanager
  template:
    metadata:
      labels:
        name: repositorymanager
    spec:
      {{- if or .Values.yuuvis.repositorymanager.core.nodeAffinity .Values.yuuvis.repositorymanager.core.podAffinity .Values.yuuvis.repositorymanager.core.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.repositorymanager.core.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.repositorymanager.core.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.repositorymanager.core.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
      containers:
      - env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.repositorymanager.core.java.maxHeap}}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{.Values.yuuvis.configservice.url}}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.repositorymanager.profile}},docker,kubernetes
        image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.repositorymanager.dockerImage}}:{{.Values.yuuvis.repositorymanager.tag}}"
        imagePullPolicy: {{.Values.yuuvis.image.imagePullPolicy}}
        name: repositorymanager
        ports:
        - containerPort: 8010
          protocol: TCP
        volumeMounts:
          - name: storage
            mountPath: {{.Values.yuuvis.repositorymanager.core.workingdir}}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: data-repositorymanager
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret}}
      initContainers:
      - name: init-repositorymanager
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      {{- with .Values.yuuvis.repositorymanager.core.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.repositorymanager.core.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.repositorymanager.core.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.repositorymanager.core.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
