apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: repositorymanager
  name: repositorymanager
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8010
  selector:
    name: repositorymanager
  type: ClusterIP