apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: repositorymanager-mq
  name: repositorymanager-mq
spec:
  ports:
    - name: dashboard
      port: 8161
    - name: openwire
      port: 61616
  selector:
    name: repositorymanager-mq
  type: ClusterIP