apiVersion: v1
kind: Service
metadata:
  labels:
    app: bpm-engine
    name: bpm-engine
  name: bpm-engine
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: bpm-engine
  type: ClusterIP