apiVersion: v1
kind: Service
metadata:
  labels:
    app: bpm-admin
    name: bpm-admin
  name: bpm-admin
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: bpm-admin
  type: ClusterIP