{{- if .Values.yuuvis.bpm.engine.database.createdb }}
apiVersion: v1
kind: Secret
metadata:
  name: initbpm-dbsecret
type: Opaque
data:
  user: {{ .Values.yuuvis.bpm.engine.database.privilege.user | b64enc | quote }}
  password: {{ .Values.yuuvis.bpm.engine.database.privilege.password | b64enc | quote }}
{{- end}}