apiVersion: v2
appVersion: "1.0"
description: Monitoring chart deploying the prometheus-operator and required resources
name: monitoring
version: 0.8.0
dependencies:
- name: kube-prometheus-stack
  version: 61.3.*
  repository: https://prometheus-community.github.io/helm-charts
