kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}     
      retention: 10d    
  grafana:
    adminPassword: changeme
    service:
      enabled: true
      type: NodePort
      targetPort: 3000

postgresql:
  postgresqlServer: postgresql
  postgresqlUser: postgres
  postgresqlPassword: changeme

# msteams webhook value replace
connectors:
  alertmanager: https://optimalsystemsgmbh.webhook.office.com/webhookb2/8ca7a7f9-c871-49d6-bc4e-b4fec75750a7@b82e583b-cea8-4382-a3a4-2905826174c5/IncomingWebhook/2af71ccf3d44426780e8cdeb4a15693b/e63251c4-a235-447c-9ece-7397c7574529