apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    # following needed to auto-bind new exporters to prometheus
    # needs to be the same label as in kubectl get svc -n {{.Values.monitor.namespace.infrastructure}} -o wide |grep prometheus-operator-operator
    release: prometheus-operator
  name: yuuvis-postgres-exporter-servicemonitor
  namespace: {{.Values.monitor.namespace.infrastructure}}
spec:
  namespaceSelector:
    matchNames:
    - {{.Values.monitor.namespace.infrastructure}}
  selector:
    matchLabels:
      app: yuuvis-postgres-exporter
  endpoints:
  - port: http
    honorLabels: true
    path: /metrics
