apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-operator
  name: repository-gateway-metrics
  namespace: {{.Values.monitor.namespace.infrastructure}}
spec:
  endpoints:
    - interval: 30s
      honorLabels: true
      path: /manage/prometheus
  jobLabel: repository
  namespaceSelector:
    matchNames:
      - {{.Values.monitor.namespace.yuuvis}}
  selector:
    matchLabels:
      app: yuuvis