apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: mailarchiving-storage
  name: mailarchiving-storage
spec:
  replicas: {{.Values.yuuvis.mailarchiving.storage.instances}}
  selector:
    matchLabels:
      name: mailarchiving-storage
  template:
    metadata:
      labels:
        name: mailarchiving-storage
    spec:
      {{- if or .Values.yuuvis.mailarchiving.storage.nodeAffinity .Values.yuuvis.mailarchiving.storage.podAffinity .Values.yuuvis.mailarchiving.storage.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.mailarchiving.storage.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.mailarchiving.storage.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.mailarchiving.storage.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: init-mailarchiving-storage
          image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
          imagePullPolicy: {{.Values.initContainer.imagePullPolicy}}
          command: [ "sh", "-c", "{{.Values.initContainer.command}}" ]
          {{- if .Values.initContainer.securityContext }}
          securityContext:
          {{- toYaml .Values.initContainer.securityContext | nindent 12 }}
          {{- end }}
      containers:
        - env:
            - name: JAVA_OPTS
              value: {{.Values.yuuvis.mailarchiving.storage.java.maxHeap}}
            - name: SPRING_CLOUD_CONFIG_URI
              value: {{.Values.yuuvis.configservice.url}}/config
            - name: SPRING_PROFILES_ACTIVE
              value: prod,mas,docker,kubernetes
            - name: DMS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.yuuvis.mailarchiving.storage.dms.passwordSecret.name}}
                  key: {{.Values.yuuvis.mailarchiving.storage.dms.passwordSecret.key}}
            {{- if .Values.yuuvis.mailarchiving.exchangeOnlineSecret.enabled }}
            - name: EXCHANGE_ONLINE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.yuuvis.mailarchiving.exchangeOnlineSecret.name}}
                  key: {{.Values.yuuvis.mailarchiving.exchangeOnlineSecret.key}}
            {{- end }}
            {{- if .Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.enabled }}
            - name: EXCHANGE_ONPREM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.name}}
                  key: {{.Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.key}}
            {{- end }}
          image: "{{.Values.yuuvis.mailarchiving.storage.dockerRegistry}}:{{.Values.yuuvis.mailarchiving.storage.tag}}"
          imagePullPolicy: {{.Values.yuuvis.image.imagePullPolicy}}
          name: mailarchiving-storage
          {{- if .Values.yuuvis.mailarchiving.storage.livenessProbe.enable }}
          livenessProbe:
            httpGet:
              path: {{.Values.yuuvis.mailarchiving.storage.livenessProbe.path}}
              port: {{.Values.yuuvis.mailarchiving.storage.port}}
            initialDelaySeconds: {{.Values.yuuvis.mailarchiving.storage.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.yuuvis.mailarchiving.storage.livenessProbe.periodSeconds }}
            timeoutSeconds: {{.Values.yuuvis.mailarchiving.storage.livenessProbe.timeoutSeconds }}
          {{- end}}
          {{- if .Values.yuuvis.mailarchiving.storage.readinessProbe.enable }}
          readinessProbe:
            httpGet:
              path: {{.Values.yuuvis.mailarchiving.storage.readinessProbe.path}}
              port: {{.Values.yuuvis.mailarchiving.storage.port}}
            initialDelaySeconds: {{.Values.yuuvis.mailarchiving.storage.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.yuuvis.mailarchiving.storage.readinessProbe.periodSeconds }}
            timeoutSeconds: {{.Values.yuuvis.mailarchiving.storage.readinessProbe.timeoutSeconds }}
          {{- end}}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          {{- with .Values.yuuvis.mailarchiving.storage.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: {{.Values.yuuvis.image.imagePullSecret}}
      restartPolicy: {{ .Values.yuuvis.mailarchiving.storage.restartPolicy }}
      {{- with .Values.yuuvis.mailarchiving.storage.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.mailarchiving.storage.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.mailarchiving.storage.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.mailarchiving.storage.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{.Values.yuuvis.mailarchiving.storage.securityContext.fsGroup}}
        runAsGroup: {{.Values.yuuvis.mailarchiving.storage.securityContext.runAsGroup}}
        runAsUser: {{.Values.yuuvis.mailarchiving.storage.securityContext.runAsUser}}
        runAsNonRoot: {{.Values.yuuvis.mailarchiving.storage.securityContext.runAsNonRoot}}
        seccompProfile:
          type: RuntimeDefault