apiVersion: v1
kind: ConfigMap
metadata:
  name:  application-mas-masstoragemomentum-prod
data:
  application-mas.yml: |
    #mas:
      #exchange-onprem:
        #access:
          #uri: https://mail.example.org/EWS/Exchange.asmx # URI of the EWS API
          #username: sample@example.org # Username of impersonation user
          #password: ${EXCHANGE_ONPREM_PASSWORD} # Password of impersonation user
      #onprem-mailbox-related-storage:
        #folder-name-config:
          #domains: test.org, testorg.onmicrosoft.com # Exchange On-premises domains for limiting mail addresses resolution. If empty there are no restrictions
          #property: USERNAME #Other values: LAST_NAME FIRST_NAME DISPLAY_NAME #Mail's propertly for controlling access. For more details, please refer to the official documentation
      #exchange-online:
        #access:
          #client-id: yyyyyyy-bbb-cccc-aaaaa-xxxxxxxx # Application authentification parameter on Azure portal.
          #tenant-id: fgfhfhh-bdf0-ghg-7668-vvvvvv  # Application authentification parameter on Azure portal.
          #secret: ${EXCHANGE_ONLINE_SECRET} # Application authentification parameter on Azure portal.
      #mailbox-related-storage:
        #folder-name-config:
          #domains: test.org,test.onmicrosoft.com # Domains that are part of the Exchange Online Active Directory
          #property: USERNAME #SAM_ACCOUNT_NAME USERNAME LAST_NAME FIRST_NAME DISPLAY_NAME #Mail's propertly for controlling access. For more details, please refer to the official documentation
  
  masstoragemomentum-prod.yml: |
    mas-storage-momentum:
      dms:
        url: {{.Values.yuuvis.mailarchiving.storage.dms.url}}
        username: {{.Values.yuuvis.mailarchiving.storage.dms.username}}
        password: ${DMS_PASSWORD}
        tenant: {{.Values.yuuvis.mailarchiving.storage.dms.tenant}}
    # user-info:
    #   url: "http://system.yuuvis/api/userinfo/${tenant}/${userId}" #The webhook URL to fetch user information
    #   mailbox-mapping:
    #     -"[mustermann@test.org]": max #Maps email addresses to internal user identifiers or names
    #     -"[kooka02@test.org]": kookatestuser03@test.org
