apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.yuuvis.labels.app}}
    name: mailarchiving-mailbox
  name: mailarchiving-mailbox
spec:
  replicas: {{.Values.yuuvis.mailarchiving.mailbox.instances}}
  selector:
    matchLabels:
      name: mailarchiving-mailbox
  template:
    metadata:
      labels:
        name: mailarchiving-mailbox
    spec:
      {{- if or .Values.yuuvis.mailarchiving.mailbox.nodeAffinity .Values.yuuvis.mailarchiving.mailbox.podAffinity .Values.yuuvis.mailarchiving.mailbox.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.mailarchiving.mailbox.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.mailarchiving.mailbox.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.mailarchiving.mailbox.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: init-mailarchiving-mailbox
          image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
          imagePullPolicy: {{.Values.yuuvis.image.imagePullPolicy}}
          command: [ "sh", "-c", "{{.Values.initContainer.command}}" ]
          {{- if .Values.initContainer.securityContext }}
          securityContext:
          {{- toYaml .Values.initContainer.securityContext | nindent 12 }}
          {{- end }}
      containers:
        - env:
            - name: JAVA_OPTS
              value: {{.Values.yuuvis.mailarchiving.mailbox.java.maxHeap}}
            - name: SPRING_CLOUD_CONFIG_URI
              value: {{.Values.yuuvis.configservice.url}}/config
            - name: SPRING_PROFILES_ACTIVE
              value: prod,mas,docker,kubernetes
            {{- if .Values.yuuvis.mailarchiving.exchangeOnlineSecret.enabled }}
            - name: EXCHANGE_ONLINE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{.Values.yuuvis.mailarchiving.exchangeOnlineSecret.name}}
                  key: {{.Values.yuuvis.mailarchiving.exchangeOnlineSecret.key}}
            {{- end }}
            {{- if .Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.enabled }}
            - name: EXCHANGE_ONPREM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.name}}
                  key: {{.Values.yuuvis.mailarchiving.exchangeOnPremPasswordSecret.key}}
            {{- end }}
          image: "{{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.mailarchiving.mailbox.image}}:{{.Values.yuuvis.mailarchiving.mailbox.tag}}"
          imagePullPolicy: {{.Values.yuuvis.image.imagePullPolicy}}
          name: mailarchiving-mailbox
          {{- if .Values.yuuvis.mailarchiving.mailbox.livenessProbe.enable }}
          livenessProbe:
            httpGet:
              path: {{.Values.yuuvis.mailarchiving.mailbox.livenessProbe.path}}
              port: {{.Values.yuuvis.mailarchiving.mailbox.port}}
            initialDelaySeconds: {{.Values.yuuvis.mailarchiving.mailbox.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.yuuvis.mailarchiving.mailbox.livenessProbe.periodSeconds }}
            timeoutSeconds: {{.Values.yuuvis.mailarchiving.mailbox.livenessProbe.timeoutSeconds }}
          {{- end}}
          {{- if .Values.yuuvis.mailarchiving.mailbox.readinessProbe.enable }}
          readinessProbe:
            httpGet:
              path: {{.Values.yuuvis.mailarchiving.mailbox.readinessProbe.path}}
              port: {{.Values.yuuvis.mailarchiving.mailbox.port}}
            initialDelaySeconds: {{.Values.yuuvis.mailarchiving.mailbox.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{.Values.yuuvis.mailarchiving.mailbox.readinessProbe.periodSeconds }}
            timeoutSeconds: {{.Values.yuuvis.mailarchiving.mailbox.readinessProbe.timeoutSeconds }}
          {{- end}}
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          {{- with .Values.yuuvis.mailarchiving.mailbox.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.yuuvis.mailarchiving.mailbox.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: {{.Values.yuuvis.image.imagePullSecret}}
      {{- with .Values.yuuvis.mailarchiving.mailbox.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.mailarchiving.mailbox.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.mailarchiving.mailbox.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.mailarchiving.mailbox.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.yuuvis.mailarchiving.mailbox.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{.Values.yuuvis.mailarchiving.mailbox.securityContext.fsGroup}}
        runAsGroup: {{.Values.yuuvis.mailarchiving.mailbox.securityContext.runAsGroup}}
        runAsUser: {{.Values.yuuvis.mailarchiving.mailbox.securityContext.runAsUser}}
        runAsNonRoot: {{.Values.yuuvis.mailarchiving.mailbox.securityContext.runAsNonRoot}}
        seccompProfile:
          type: RuntimeDefault