apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: repositorymanager-al
  name: repositorymanager-al
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8092
  selector:
    name: repositorymanager-al
  type: ClusterIP