imageCredentials:
  yuuvisorg:
    registry: docker.yuuvis.org
    username:
    password:
yuuvis:
  labels:
    app: yuuvis
  image:
    imagePullPolicy: Always
    imagePullSecret: yuuvisorgsmtp
  configservice:
    url: http://system.yuuvis #change  value if system is in another namespace not yuuvis e.g. http://system.2021winter
  mailarchiving:
    exchangeOnPremPasswordSecret:
      enabled: false
      name: exchange-onprem-secret-name # please change the value if it is in script different
      key: exchange-onprem-secret-key # please change the value if it is in script different
    exchangeOnlineSecret:
      enabled: false
      name: exchange-online-secret-name # please change the value if it is in script different
      key: exchange-online-secret-key # please change the value if it is in script different
    initContainerImage: docker.yuuvis.org/yuuvis/helper/init-helper:latest
    smtp:
      instances: 1
      dockerRegistry: docker.yuuvis.org/yuuvis/mailarchiving-smtp
      tag: 2.2.1
      resources:
        requests:
          cpu: "0.2"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2000Mi"
      java:
        maxHeap: -Xmx256m -XX:+ExitOnOutOfMemoryError
      profiles:
        masstorage:
          uri: http://mailarchiving-storage #if it is in another namespace, please change value e.g. http://mailarchiving-storage.kookaburra
      pdb:
        # pdb requires instances > 1 and  minAvailable < instances,
        # otherwise draining nodes will deadlock!
        enabled: false

        # set `minAvailable: null` if you want to use maxUnavailable instead
        minAvailable: 1
      nodeSelector: { }
      priorityClassName: ""
      tolerations: [ ]
      nodeAffinity: { }
      podAffinity: { }
      podAntiAffinity: { }

# please change value of system service namespace e.g. http://system.2024winter
initContainer:
  command: "until wget -q --spider http://system.yuuvis/manage/health; do echo waiting for config; sleep 11; done;"