imageCredentials:
  yuuvisorg:
    registry: docker.yuuvis.org
    username:
    password:
yuuvis:
  labels:
    app: yuuvis
  image:
    imagePullPolicy: IfNotPresent
    dockerRegistry: docker.yuuvis.org
    imagePullSecret: yuuvisorgsmtp
    restartPolicy: OnFailure
  configservice:
    url: http://system.yuuvis #change  value if system is in another namespace not yuuvis e.g. http://system.2021winter
  mailarchiving:
    # --- Basic Authentication for Exchange On-premises ---
    # Enable and configure these fields ONLY if you are using Basic Authentication with Exchange On-premises.
    exchangeOnPremPasswordSecret:
      enabled: false
      name: exchange-onprem-secret-name # please change the value if it is in script different
      key: exchange-onprem-secret-key # please change the value if it is in script different
    # Enable and configure these fields ONLY if you are using Exchange Online.
    exchangeOnlineSecret:
      enabled: false
      name: exchange-online-secret-name # please change the value if it is in script different
      key: exchange-online-secret-key # please change the value if it is in script different
    # --- Oauth2 Authentication for Exchange On-premises ---
    # Enable and configure these fields ONLY if you are using OAuth2 Authentication with Exchange On-premises.
    exchangeOnPremOAuth2:
      enabled: false
      clientCertificateName: exchange-onprem-client-certificate-name
      clientCertificateKey: exchange-onprem-client-certificate-key
      clientPrivateKeyName: exchange-onprem-client-private-key-name
      clientPrivateKeyKey: exchange-onprem-client-private-key-key
    initContainer:
      image: yuuvis/helper/init-helper
      tag: latest
      tolerations: [ ]
      nodeAffinity: { }
      securityContext: { }
      backoffLimit: 3
      ttlSecondsAfterFinished: 3600 #job will be deleted after 1 hour
    selfSignedCert:
      image: yuuvis/helper/create-selfsigned-cert
      tag: jre11
      reinstallifexists: false # set to true if you want to reinstall certificate on chart upgrade
      password: optimal1! # change the password or use default value
    smtp:
      instances: 1
      image: yuuvis/mailarchiving-smtp
      tag: 2.2.5
      resources:
        requests:
          cpu: "0.2"
          memory: "512Mi"
        limits:
          cpu: "2"
          memory: "2000Mi"
      java:
        maxHeap: -Xmx256m -XX:+ExitOnOutOfMemoryError
      profiles:
        masstorage:
          uri: http://mailarchiving-storage #if it is in another namespace, please change value e.g. http://mailarchiving-storage.kookaburra
      port: 8120
      securityContext:
        fsGroup: 2000
        runAsGroup: 3000
        runAsUser: 1000
        runAsNonRoot: true
      livenessProbe:
        enable: true
        initialDelaySeconds: 300
        periodSeconds: 30
        timeoutSeconds: 10
        path: /manage/info
      readinessProbe:
        enable: true
        initialDelaySeconds: 0
        periodSeconds: 30
        timeoutSeconds: 5
        path: /manage/health
      pdb:
        # pdb requires instances > 1 and  minAvailable < instances,
        # otherwise draining nodes will deadlock!
        enabled: false

        # set `minAvailable: null` if you want to use maxUnavailable instead
        minAvailable: 1
      nodeSelector: { }
      priorityClassName: ""
      tolerations: [ ]
      nodeAffinity: { }
      podAffinity: { }
      podAntiAffinity: { }

# please change value of system service namespace e.g. http://system.2024winter and mailarchiving-storage e.g. http://mailarchiving-storage.kookaburra
initContainer:
  command: "until wget -q --spider http://system/manage/health && wget -q --spider http://mailarchiving-storage/manage/health; do echo waiting for services; sleep 11; done;"
  image: library/busybox
  tag: 1.36
  securityContext: { }