apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: Authorization,X-ID-TENANT-NAME,DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.monitoring.address }}
    http:
      paths:
      - backend:
          service:
            name: monitoring-grafana
            port:
              number: 3000
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.monitoring.address }}
    secretName: traces-enaioci-net-cert