---
apiVersion: v1
kind: ConfigMap
metadata:
  name: query
  namespace: {{.Values.monitor.namespace.infrastructure}}
data:
  query.yml: |
    pg_replication:
      query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as lag"
      master: true
      metrics:
        - lag:
            usage: "GAUGE"
            description: "Replication lag behind master in seconds"   
    tcp_ping:
      query: "SELECT 1 as check_label"
      master: true
      metrics:
        - check:
            usage: "GAUGE"
            description: "High availability check"   
    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size_bytes FROM pg_database WHERE datname NOT LIKE 'template%'"
      master: true
      cache_seconds: 30
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size_bytes:
            usage: "GAUGE"
            description: "Disk space used by the database"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuuvis-postgres-exporter
  namespace: {{.Values.monitor.namespace.infrastructure}}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: yuuvis-postgres-exporter
  template:
    metadata:
      labels:
        app: yuuvis-postgres-exporter
    spec:
      containers:
        - name: yuuvis-postgres-exporter
          image: wrouesnel/postgres_exporter
          env:
          - name: DATA_SOURCE_URI
            value: "{{.Values.postgresql.postgresqlServer}}:5432?sslmode=disable"
          - name: DATA_SOURCE_USER
            value: "{{.Values.postgresql.postgresqlUser}}"
          - name: DATA_SOURCE_PASS
            value: "{{.Values.postgresql.postgresqlPassword}}"
          - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
            value: "true" 
          - name: PG_EXPORTER_EXTEND_QUERY_PATH
            value: "/mnt/query.yml"
          ports:
          - containerPort: 9187
          volumeMounts:
          - name: "query"
            mountPath: "/mnt/query.yml"
            subPath: "query.yml"
      volumes:
        - name: "query"
          configMap:
            name: "query"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: yuuvis-postgres-exporter
  namespace: {{.Values.monitor.namespace.infrastructure}}
  labels:
    app: yuuvis-postgres-exporter
spec:
  clusterIP: None
  selector:
    app: yuuvis-postgres-exporter
  ports:
    - name: http
      port: 9187
      protocol: TCP

