apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: yuuvis-metrics
spec:
  endpoints:
  - port: http
    path: /manage/prometheus  
  namespaceSelector:
    matchNames:
    - yuuvis
  selector:
    matchLabels:
      app: yuuvis