apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: yuuvis
  name: create-selfsigned-cert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secretsrole
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: systemrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secretsrole
subjects:
- kind: ServiceAccount
  name: create-selfsigned-cert