apiVersion: v1
kind: Service
metadata:
  labels:
    app: rendition
    name: rendition
    yuuvis: "true"
  name: rendition
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7341
  selector:
    name: rendition
  type: ClusterIP