{{- if .Values.yuuvis.renditiontextworker.yuuvis.user.createnewsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.secretname }}
type: Opaque
data:
  tenant: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.tenant | b64enc | quote }}
  user: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.username | b64enc | quote }}
  password: {{ .Values.yuuvis.renditiontextworker.yuuvis.user.password | b64enc | quote }}
{{- end -}}
