apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rendition
    name: renditionrepository
  name: renditionrepository
spec:
  replicas: {{.Values.yuuvis.renditionrepository.instances}}
  selector:
    matchLabels:
      name: renditionrepository
  template:
    metadata:
      labels:
        name: renditionrepository
    spec:
      {{- if or .Values.yuuvis.renditionrepository.nodeAffinity .Values.yuuvis.renditionrepository.podAffinity .Values.yuuvis.renditionrepository.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.renditionrepository.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.renditionrepository.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.renditionrepository.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: renditionrepository
        image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.renditionrepository.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /manage/info
            port: 9876
          initialDelaySeconds: {{.Values.yuuvis.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.livenessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: /manage/info
            port: 9876
          initialDelaySeconds: {{.Values.yuuvis.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{.Values.yuuvis.readinessProbe.periodSeconds }}
          timeoutSeconds: {{.Values.yuuvis.readinessProbe.timeoutSeconds }}
        env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.renditionrepository.java.options}}
        - name: SERVER_PORT
          value: "9876"
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.renditionrepository.profiles}}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{ .Values.yuuvis.configservice.url }}
        ports:
        - containerPort: 9876
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret}}
      initContainers:
      - name: init-renditionrepository
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      {{- with .Values.yuuvis.renditionrepository.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.renditionrepository.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.api.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.renditionrepository.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}