apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yuuvis
    name: rendition
  name: rendition
spec:
  replicas: {{.Values.yuuvis.renditionservice.instances}}
  selector:
    matchLabels:
      name: rendition
  template:
    metadata:
      labels:
        name: rendition
    spec:
      {{- if or .Values.yuuvis.renditionservice.nodeAffinity .Values.yuuvis.renditionservice.podAffinity .Values.yuuvis.renditionservice.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.renditionservice.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.renditionservice.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.renditionservice.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - env:
        - name: JAVA_OPTS
          value: {{.Values.yuuvis.renditionservice.java.maxHeap}}
        - name: SPRING_CLOUD_CONFIG_URI
          value: {{ .Values.yuuvis.configservice.url }}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.yuuvis.renditionservice.profiles}}
        image: {{.Values.yuuvis.image.dockerRegistry}}/{{.Values.yuuvis.renditionservice.dockerImage}}
        imagePullPolicy: {{ .Values.yuuvis.image.imagePullPolicy }}
        name: rendition
        ports:
        - containerPort: 7341
          protocol: TCP
      imagePullSecrets:
      - name: {{.Values.yuuvis.image.imagePullSecret}}
      initContainers:
      - name: init-rendition
        image: "{{.Values.initContainer.dockerRegistry}}/{{.Values.initContainer.image}}:{{.Values.initContainer.tag}}"
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "{{.Values.initContainer.command}}"]
      {{- with .Values.yuuvis.renditionservice.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.renditionservice.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.services.api.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.renditionservice.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}