apiVersion: v1
kind: Service
metadata:
  labels:
    app: rendition
    name: renditionrepository
  name: renditionrepository
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 9876
  selector:
    name: renditionrepository
  type: ClusterIP