{{- if .Values.gitea.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-init
  labels:
    app: giteainit
spec:
  template:
    spec:
      {{- if or .Values.yuuvis.git.initcontainer.nodeAffinity .Values.yuuvis.git.initcontainer.podAffinity .Values.yuuvis.git.initcontainer.podAntiAffinity }}
      affinity:
        {{- with .Values.yuuvis.git.initcontainer.nodeAffinity }}
        nodeAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.git.initcontainer.podAffinity }}
        podAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.yuuvis.git.initcontainer.podAntiAffinity }}
        podAntiAffinity: {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: gitea-init
        image: {{.Values.yuuvis.git.initcontainer.image}}
        imagePullPolicy: IfNotPresent
        command: ['sh', '/yuuvis/script/gitInitRepo.sh']
        volumeMounts:
        - mountPath: /yuuvis/script/gitInitRepo.sh
          name: initscript
          subPath: gitInitRepo.sh
      imagePullSecrets:
      - name:  {{.Values.yuuvis.git.initcontainer.secret}}
      volumes:
      - configMap:
          name: gitinitrepo
        name: initscript
      restartPolicy: OnFailure
      {{- with .Values.yuuvis.git.initcontainer.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.yuuvis.git.initcontainer.priorityClassName }}
      priorityClassName: {{ .Values.yuuvis.git.initcontainer.priorityClassName }}
      {{- end }}
      {{- with .Values.yuuvis.git.initcontainer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}