{{- if .Values.gogs.useCustomDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gogs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gogs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gogs
    spec:
      containers:
      - env:
        - name: SOCAT_LINK
          value: "false"
        image: {{.Values.gogs.image}}
        imagePullPolicy: {{.Values.gogs.imagePullPolicy}}
        name: gogs
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /data/gogs/conf/app.ini
          name: config
          subPath: app.ini
      volumes:
      - configMap:
          name: gogs-config
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: gogs
---
apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
  - name: gogs-http
    port: 80
    targetPort: 3000
  selector:
    app: gogs
  type: ClusterIP
status:
  loadBalancer: {}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gogs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.gogs.persistence.size}}
  storageClassName: {{.Values.gogs.persistence.storageClassName}}    
---
apiVersion: v1
data:
  app.ini: "APP_NAME = Gogs\nRUN_MODE = prod\n\n[repository.upload]\nENABLED = true\nALLOWED_TYPES
    = \nMAX_FILE_SIZE = 10\nMAX_FILES = 10\n\n[server]\nPROTOCOL = http\nDOMAIN =
    gogs.example.com\nROOT_URL = http://gogs.example.com/\nLANDING_PAGE = home\nSSH_DOMAIN
    = localhost\nSSH_PORT = 22\nSSH_LISTEN_PORT = 22\n\n[service]\nENABLE_CAPTCHA
    = false\nACTIVE_CODE_LIVE_MINUTES = 180\nRESET_PASSWD_CODE_LIVE_MINUTES = 180\nREGISTER_EMAIL_CONFIRM
    = false\nDISABLE_REGISTRATION = false\nREQUIRE_SIGNIN_VIEW = false\nENABLE_NOTIFY_MAIL
    = false\nENABLE_REVERSE_PROXY_AUTHENTICATION = false\nENABLE_REVERSE_PROXY_AUTO_REGISTRATION
    = false\n\n[database]\nDB_TYPE = \"sqlite3\"\nHOST = \"127.0.0.1\"\nNAME
    = \"gogs\"\n\n[security]\nINSTALL_LOCK
    = true\nSECRET_KEY = \"b3B0aW1hbA==\"\n\n[ui]\nEXPLORE_PAGING_NUM = 20\nISSUE_PAGING_NUM
    = 10\nFEED_MAX_COMMIT_NUM = 5\n\n[cache]\nADAPTER = memory\nINTERVAL = 60\nHOST
    = \n\n[webhook]\nQUEUE_LENGTH = 1000\nDELIVER_TIMEOUT = 5\nSKIP_TLS_VERIFY = true\nPAGING_NUM
    = 10\n\n[log]\nMODE = console\nLEVEL = Trace\n\n[other]\nSHOW_FOOTER_BRANDING
    = false\nSHOW_FOOTER_VERSION = true\nSHOW_FOOTER_TEMPLATE_LOAD_TIME = true"
kind: ConfigMap
metadata:
  labels:
    app: gogs-config
  name: gogs-config
{{- end}}
