{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    name: keycloak-https
  name: keycloak-https
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    nodePort: {{.Values.yuuvis.keycloak.nodePort}}
  selector:
    app.kubernetes.io/instance: {{.Release.Namespace}}
    app.kubernetes.io/name: keycloak
  type: NodePort
{{- end}}