{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
data:
  create_enaio_dbs.sql: |
    CREATE DATABASE {{.Values.yuuvis.db.name}};
    CREATE USER {{.Values.yuuvis.db.user}} WITH ENCRYPTED PASSWORD '{{.Values.yuuvis.db.password}}';
    GRANT ALL PRIVILEGES ON DATABASE yuuvis TO {{.Values.yuuvis.db.user}};
{{- if .Values.keycloak.enabled }}
    CREATE DATABASE {{.Values.keycloak.database.database}};
    CREATE USER {{.Values.keycloak.database.username}} WITH ENCRYPTED PASSWORD '{{.Values.keycloak.database.password}}';
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO {{.Values.keycloak.database.username}};
{{- end}}
{{- end}}