apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: create-keycloak-cert
  name: create-selfsigned-cert
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: create-keycloak-cert
  name: create-selfsigned-cert
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-selfsigned-cert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-selfsigned-cert
subjects:
- kind: ServiceAccount
  name: create-selfsigned-cert
  namespace: {{.Values.yuuvis.namespaces.infrastructure}}