apiVersion: v2
appVersion: "1.0"
description: umbrella chart with examples for infrastructure components of an yuuvis API installation
             infrastructure components include a database, an identity provider, storage etc.
             this chart is for demo use only 
             do not use this chart for production
name: infrastructure
version: 0.12.1
dependencies:
- name: minio
  version: ^4.0.7
  repository: https://charts.min.io/
  condition: minio.enabled
- name: keycloakx
  version: ^1.6.1
  repository: https://codecentric.github.io/helm-charts/
  condition: keycloak.enabled
  alias: keycloak
- name: redis
  version: ~17.15.3
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: postgresql
  version: ^11.6.16
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: rabbitmq
  version: ^10.1.14
  repository: https://charts.bitnami.com/bitnami 
  condition: rabbitmq.enabled
- name: gitea
  version: ^5.0.9
  repository: https://dl.gitea.io/charts/
  condition: gitea.enabled