apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: repositorymanager-ilm
  name: repositorymanager-ilm
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8091
  selector:
    name: repositorymanager-ilm
  type: ClusterIP