apiVersion: v1
kind: Service
metadata:
  labels:
    app: yuuvis
    name: mailarchiving-storage
  name: mailarchiving-storage
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8130
  selector:
    name: mailarchiving-storage
  type: ClusterIP